epoch_size: 50
warm_start: 1
warm_start_epoch_number: 20
train_mode: 0
allow_wrong_service: 1
max_turn: 10
saved_model: model/model_d_agent_dqn_s1.0_r36.4_t3.36_wd0.0_e49.pkl
input_size_dqn: 1122
hidden_size_dqn: 300
experience_replay_pool_size: 20000
epsilon: 0.1
gamma: 1.0
dqn_learning_rate: 0.001
save_performance: 0
performance_save_path: /home/yanking/disk1/nizepu/govChatbot/model/dqn/learning_rate